#!/usr/bin/python
# -*- coding: UTF-8 -**-


class Employee(object):
	def Employee(self):
		pass

	def getName(self):
		return self.___name

	def setName(self, aName) -> None:
		self.___name = aName

	def __init__(self):
		self.___name = None

